/* ------------------------------------------------------------------
 * blueprint · embedded templates
 * The same idea as the real CLI: every template lives in one file and
 * is rendered with plain string substitution. Zero dependencies.
 * ------------------------------------------------------------------ */

export type LicenseId = "MIT" | "Apache-2.0" | "none";

export interface ProjectConfig {
  name: string;
  description: string;
  author: string;
  license: LicenseId;
}

export interface GeneratedFile {
  path: string;
  lang: Lang;
  content: string;
  bytes: number;
}

export type Lang = "toml" | "markdown" | "yaml" | "python" | "json" | "text";

export const LICENSES: { id: LicenseId; label: string }[] = [
  { id: "MIT", label: "MIT" },
  { id: "Apache-2.0", label: "Apache-2.0" },
  { id: "none", label: "none" },
];

/* ---------------- naming helpers ---------------- */

export function slugify(raw: string): string {
  const s = raw
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return s || "my-project";
}

export function toModule(slug: string): string {
  let m = slug.replace(/-/g, "_");
  if (/^[0-9]/.test(m)) m = "_" + m;
  return m || "my_project";
}

export function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  return `${(n / 1024).toFixed(1)} KB`;
}

const enc = new TextEncoder();
const size = (s: string) => enc.encode(s).length;

interface Ctx {
  slug: string;
  module: string;
  description: string;
  author: string;
  year: string;
  iso: string;
}

function fill(tpl: string, ctx: Record<string, string>): string {
  return tpl.replace(/\{\{(\w+)\}\}/g, (_, k: string) => ctx[k] ?? "");
}

/* ---------------- templates ---------------- */

const T_PYPROJECT = `
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{{slug}}"
version = "0.1.0"
description = "{{description}}"
readme = "README.md"
authors = [{ name = "{{author}}" }]
requires-python = ">=3.10"
{{licenseLine}}keywords = ["billybox", "{{slug}}"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Software Development :: Build Tools",
]

[project.scripts]
{{module}} = "{{module}}.main:main"

[project.urls]
Homepage = "https://github.com/billybox/{{slug}}"
Issues = "https://github.com/billybox/{{slug}}/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/{{module}}"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.mypy]
strict = true
python_version = "3.10"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
`;

const T_README = `
# {{slug}}

> {{description}}

[![PyPI version](https://img.shields.io/pypi/v/{{slug}}?color=57aeff)](https://pypi.org/project/{{slug}}/)
[![ci](https://github.com/billybox/{{slug}}/actions/workflows/ci.yml/badge.svg)](https://github.com/billybox/{{slug}}/actions/workflows/ci.yml)
[![python](https://img.shields.io/pypi/pyversions/{{slug}})](https://pypi.org/project/{{slug}}/)
[![ruff](https://img.shields.io/badge/lint-ruff-57aeff)](https://docs.astral.sh/ruff/)
{{licenseBadge}}
## Install

\\\`\\\`\\\`bash
pip install {{slug}}
\\\`\\\`\\\`

## Quickstart

\\\`\\\`\\\`bash
{{module}} --version
{{module}} --help
\\\`\\\`\\\`

## Development

\\\`\\\`\\\`bash
pip install -e .
pip install ruff mypy pytest
ruff check . && ruff format --check .
mypy src
pytest
\\\`\\\`\\\`

Pre-commit hooks enforce the BillyBox standard on every commit —
see \\\`.pre-commit-config.yaml\\\`.

## BillyBox wiring

This repo ships pre-wired for the BillyBox suite:

| File              | Purpose                                   |
| ----------------- | ----------------------------------------- |
| \\\`bb.json\\\`         | project identity + suite defaults         |
| \\\`policy.json\\\`     | policies checked by \\\`policy-runner\\\`     |
| \\\`routes.json\\\`     | fixtures served by \\\`mockroute\\\`          |
| \\\`commitlog.json\\\`  | release notes consumed by \\\`commitlog\\\`   |
| \\\`.ctxignore\\\`      | keep \\\`ctxpack\\\` context lean             |

Run \\\`bb preflight\\\` before cutting a release.

---

Part of the [BillyBox suite](https://github.com/billybox) · generated by **blueprint v0.1.0**
`;

const T_LICENSE_MIT = `
MIT License

Copyright (c) {{year}} {{author}}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;

const T_LICENSE_APACHE = `
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      [... Sections 2–9: grant of license, redistribution, notices,
           contributions, trademarks, disclaimer of warranty,
           limitation of liability, accepting warranties, indemnity ...]

   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.

   Copyright {{year}} {{author}}

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
   implied. See the License for the specific language governing
   permissions and limitations under the License.
`;

const T_GITIGNORE = `
# --- python ---
__pycache__/
*.py[cod]
*.egg-info/
build/
dist/
wheels/

# --- environments ---
.venv/
venv/
.env
.env.*

# --- tooling caches ---
.mypy_cache/
.pytest_cache/
.ruff_cache/
.coverage
htmlcov/

# --- os / editor ---
.DS_Store
.idea/
.vscode/
`;

const T_PRECOMMIT = `
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--strict, src]
`;

const T_CI = `
name: ci

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install
        run: |
          pip install -e .
          pip install ruff mypy
      - name: Lint (ruff)
        run: ruff check . && ruff format --check .
      - name: Types (mypy --strict)
        run: mypy src

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: \${{ matrix.python-version }}
      - name: Install
        run: |
          pip install -e .
          pip install pytest
      - name: Test (pytest)
        run: pytest
`;

const T_PUBLISH = `
name: publish

on:
  push:
    tags: ["v*"]

jobs:
  guard:
    # Tag-vs-wheel guard: refuse to publish when the pushed tag
    # does not match the version baked into pyproject.toml.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Tag ↔ wheel guard
        run: |
          set -euo pipefail
          TAG="\${GITHUB_REF_NAME#v}"
          VER="$(python -c "import tomllib;print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")"
          echo "tag=v$TAG · wheel=$VER"
          test "$TAG" = "$VER" || { echo "::error::v$TAG ≠ $VER — refusing to publish"; exit 1; }

  build:
    needs: guard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install build
      - run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC trusted publishing — no long-lived PyPI tokens
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
`;

const T_INIT_PY = `
"""{{description}}"""

__version__ = "0.1.0"
`;

const T_MAIN_PY = `
"""{{description}}

CLI entry point — wired by blueprint v0.1.0.
"""
from __future__ import annotations

import argparse

from {{module}} import __version__


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="{{module}}",
        description="{{description}}",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    parser.parse_args(argv)
    print("{{slug}} is wired and waiting — implement me.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
`;

const T_TEST_MAIN = `
from {{module}} import __version__
from {{module}}.main import main


def test_version() -> None:
    assert __version__ == "0.1.0"


def test_main_returns_zero() -> None:
    assert main([]) == 0
`;

const T_DOCS_INDEX = `
# {{slug}} — documentation skeleton

Generated by **blueprint v0.1.0**. Fill these in before the first release.

## Contents

1. [Overview](#overview)
2. [Install](#install)
3. [Usage](#usage)
4. [Configuration](#configuration)

## Overview

_TODO — what does {{slug}} do, and why does it exist?_

## Install

\\\`\\\`\\\`bash
pip install {{slug}}
\\\`\\\`\\\`

## Usage

\\\`\\\`\\\`bash
{{module}} --help
\\\`\\\`\\\`

_TODO — document every flag and exit code._

## Configuration

{{slug}} reads BillyBox wiring from the repo root:
\\\`bb.json\\\`, \\\`policy.json\\\`, \\\`routes.json\\\`, \\\`commitlog.json\\\`.

_TODO — document each knob._
`;

const T_BB_JSON = `
{
  "project": "{{slug}}",
  "suite": "billybox",
  "blueprint": {
    "version": "0.1.0",
    "template": "python-cli",
    "generated_at": "{{iso}}"
  },
  "defaults": {
    "python": ">=3.10",
    "ci": true,
    "publish": "oidc-trusted"
  }
}
`;

const T_CTXIGNORE = `
# keep ctxpack context lean — nothing generated or vendored
.git/
.venv/
dist/
build/
*.egg-info/
__pycache__/
.mypy_cache/
.pytest_cache/
.ruff_cache/
htmlcov/
*.pyc
`;

const T_POLICY_JSON = `
{
  "version": 1,
  "policies": [
    {
      "id": "P-001",
      "name": "no secrets in repo",
      "severity": "block",
      "check": "secrets-scan"
    },
    {
      "id": "P-002",
      "name": "version tag matches wheel",
      "severity": "block",
      "check": "tag-wheel-guard"
    },
    {
      "id": "P-003",
      "name": "release notes present",
      "severity": "warn",
      "check": "commitlog-entry"
    }
  ]
}
`;

const T_ROUTES_JSON = `
{
  "version": 1,
  "routes": [
    {
      "name": "health",
      "method": "GET",
      "path": "/healthz",
      "status": 200,
      "body": { "ok": true, "service": "{{slug}}" }
    }
  ]
}
`;

const T_COMMITLOG_JSON = `
{
  "version": 1,
  "project": "{{slug}}",
  "entries": []
}
`;

/* ---------------- renderer ---------------- */

export function renderProject(cfg: ProjectConfig): GeneratedFile[] {
  const slug = slugify(cfg.name);
  const module = toModule(slug);
  const description = cfg.description.trim() || "A BillyBox tool.";
  const author = cfg.author.trim() || "Billy Box";
  const year = String(new Date().getFullYear());
  const iso = `${year}-01-01T00:00:00Z`;

  const ctx: Ctx = { slug, module, description, author, year, iso };
  const vars: Record<string, string> = { ...ctx };

  const licenseLine =
    cfg.license === "none" ? "" : `license = "${cfg.license}"\n`;
  const licenseBadge =
    cfg.license === "none"
      ? ""
      : `[![license](https://img.shields.io/pypi/l/${slug})](./LICENSE)\n`;

  const mk = (path: string, lang: Lang, tpl: string): GeneratedFile => {
    const content = fill(tpl, { ...vars, licenseLine, licenseBadge }).replace(
      /^\n/,
      "",
    );
    return { path, lang, content, bytes: size(content) };
  };

  const files: GeneratedFile[] = [
    mk("pyproject.toml", "toml", T_PYPROJECT),
    mk("README.md", "markdown", T_README),
  ];

  if (cfg.license === "MIT") files.push(mk("LICENSE", "text", T_LICENSE_MIT));
  if (cfg.license === "Apache-2.0")
    files.push(mk("LICENSE", "text", T_LICENSE_APACHE));

  files.push(
    mk(".gitignore", "text", T_GITIGNORE),
    mk(".pre-commit-config.yaml", "yaml", T_PRECOMMIT),
    mk(".github/workflows/ci.yml", "yaml", T_CI),
    mk(".github/workflows/publish.yml", "yaml", T_PUBLISH),
    mk(`src/${module}/__init__.py`, "python", T_INIT_PY),
    mk(`src/${module}/main.py`, "python", T_MAIN_PY),
    mk("tests/test_main.py", "python", T_TEST_MAIN),
    mk("docs/index.md", "markdown", T_DOCS_INDEX),
    mk("bb.json", "json", T_BB_JSON),
    mk(".ctxignore", "text", T_CTXIGNORE),
    mk("policy.json", "json", T_POLICY_JSON),
    mk("routes.json", "json", T_ROUTES_JSON),
    mk("commitlog.json", "json", T_COMMITLOG_JSON),
  );

  return files;
}

export const DEFAULT_CONFIG: ProjectConfig = {
  name: "local-drift",
  description: "Local config drift detector",
  author: "Billy Box",
  license: "MIT",
};

/* notes shown in the file viewer */
export const FILE_NOTES: Record<string, string> = {
  "pyproject.toml": "hatchling build · script entry point · ruff/mypy/pytest config",
  "README.md": "badges, quickstart, and the BillyBox wiring table",
  LICENSE: "full text embedded — MIT by default, Apache-2.0 on request",
  ".gitignore": "python + venv + tooling caches",
  ".pre-commit-config.yaml": "the BillyBox pre-commit standard",
  ".github/workflows/ci.yml": "ruff + mypy on 3.12 · pytest matrix 3.10→3.13",
  ".github/workflows/publish.yml": "tag-vs-wheel guard · OIDC trusted publishing",
  "__init__.py": "single source of truth for __version__",
  "main.py": "argparse skeleton — the script entry point lands here",
  "test_main.py": "one passing test on day one",
  "index.md": "docs skeleton with TODOs, not lorem",
  "bb.json": "project identity for the whole suite",
  ".ctxignore": "keeps ctxpack context lean",
  "policy.json": "seed policies for policy-runner",
  "routes.json": "seed fixture for mockroute",
  "commitlog.json": "empty ledger, ready for commitlog",
};
