/* ------------------------------------------------------------------
 * blueprint · embedded template bodies (as-built, v0.1.0)
 * Ported verbatim from the shipped blueprint.py.
 * ------------------------------------------------------------------ */

export const T_PYPROJECT = `
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "$project_name"
version = "0.1.0"
description = "$description"
readme = "README.md"
authors = [{ name = "$author" }]
requires-python = ">=3.10"
$licenseLinekeywords = ["billybox", "$project_name"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Software Development :: Build Tools",
]

[project.scripts]
$package_name = "$package_name.main:main"

[project.urls]
Homepage = "https://github.com/billybox/$project_name"
Issues = "https://github.com/billybox/$project_name/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/$package_name"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.mypy]
strict = true
python_version = "3.10"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
`;

export const T_README = `
# $project_name

> $description

[![PyPI version](https://img.shields.io/pypi/v/$project_name?color=57aeff)](https://pypi.org/project/$project_name/)
[![ci](https://github.com/billybox/$project_name/actions/workflows/ci.yml/badge.svg)](https://github.com/billybox/$project_name/actions/workflows/ci.yml)
[![python](https://img.shields.io/pypi/pyversions/$project_name)](https://pypi.org/project/$project_name/)
[![ruff](https://img.shields.io/badge/lint-ruff-57aeff)](https://docs.astral.sh/ruff/)
$licenseBadge
## Install

\`\`\`bash
pip install $project_name
\`\`\`

## Quickstart

\`\`\`bash
$package_name --version
$package_name --help
\`\`\`

## Development

\`\`\`bash
pip install -e .
pip install ruff mypy pytest
ruff check . && ruff format --check .
mypy src
pytest
\`\`\`

Pre-commit hooks enforce the BillyBox standard on every commit —
see \`.pre-commit-config.yaml\`.

## BillyBox wiring

This repo ships pre-wired for the BillyBox suite:

| File              | Purpose                                   |
| ----------------- | ----------------------------------------- |
| \`bb.json\`         | project identity + suite defaults         |
| \`policy.json\`     | policies checked by \`policy-runner\`       |
| \`routes.json\`     | fixtures served by \`mockroute\`            |
| \`commitlog.json\`  | release notes consumed by \`commitlog\`     |
| \`.ctxignore\`      | keep \`ctxpack\` context lean               |

Run \`bb preflight\` before cutting a release.

---

Part of the [BillyBox suite](https://github.com/billybox) · generated by **blueprint v0.1.0**
`;

export const T_LICENSE_MIT = `
MIT License

Copyright (c) $year $author

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;

export const T_LICENSE_APACHE = `
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      [... Sections 2-9: grant of license, redistribution, notices,
           contributions, trademarks, disclaimer of warranty,
           limitation of liability, accepting warranties, indemnity ...]

   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.

   Copyright $year $author

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
`;

export const T_GITIGNORE = `
# --- python ---
__pycache__/
*.py[cod]
*.egg-info/
build/
dist/
wheels/

# --- environments ---
.venv/
venv/
.env
.env.*

# --- tooling caches ---
.mypy_cache/
.pytest_cache/
.ruff_cache/
.coverage
htmlcov/

# --- os / editor ---
.DS_Store
.idea/
.vscode/
`;

export const T_PRECOMMIT = `
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--strict, src]
`;

export const T_CI = `
name: ci

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install
        run: |
          pip install -e .
          pip install ruff mypy
      - name: Lint (ruff)
        run: ruff check . && ruff format --check .
      - name: Types (mypy --strict)
        run: mypy src

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: \${{ matrix.python-version }}
      - name: Install
        run: |
          pip install -e .
          pip install pytest
      - name: Test (pytest)
        run: pytest
`;

export const T_PUBLISH = `
name: publish

on:
  push:
    tags: ["v*"]

jobs:
  guard:
    # Tag-vs-wheel guard: refuse to publish when the pushed tag
    # does not match the version baked into pyproject.toml.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Tag <-> wheel guard
        run: |
          set -euo pipefail
          TAG="\${GITHUB_REF_NAME#v}"
          VER="$(python -c "import tomllib;print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")"
          echo "tag=v$TAG - wheel=$VER"
          test "$TAG" = "$VER" || { echo "::error::v$TAG != $VER - refusing to publish"; exit 1; }

  build:
    needs: guard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install build
      - run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC trusted publishing - no long-lived PyPI tokens
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
`;

export const T_INIT = `
"""$description"""

__version__ = "0.1.0"
`;

export const T_MAIN = `#!/usr/bin/env python3
"""$description

CLI entry point - wired by blueprint v0.1.0.
"""
from __future__ import annotations

import argparse

from $package_name import __version__


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="$package_name",
        description="$description",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    parser.parse_args(argv)
    print("$project_name is wired and waiting - implement me.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
`;

export const T_TEST = `
from $package_name import __version__
from $package_name.main import main


def test_version() -> None:
    assert __version__ == "0.1.0"


def test_main_returns_zero() -> None:
    assert main([]) == 0
`;

export const T_DOCS_INDEX = `
# $project_name - documentation skeleton

Generated by **blueprint v0.1.0**. Fill these in before the first release.

## Contents

1. [Overview](#overview)
2. [Install](#install)
3. [Usage](#usage)
4. [Configuration](#configuration)

## Overview

_TODO - what does $project_name do, and why does it exist?_

## Install

\`\`\`bash
pip install $project_name
\`\`\`

## Usage

\`\`\`bash
$package_name --help
\`\`\`

_TODO - document every flag and exit code._

## Configuration

$project_name reads BillyBox wiring from the repo root:

\`bb.json\`, \`policy.json\`, \`routes.json\`, \`commitlog.json\`.

_TODO - document each knob._
`;

export const T_BB_JSON = `
{
  "project": "$project_name",
  "suite": "billybox",
  "blueprint": {
    "version": "0.1.0",
    "template": "python-cli",
    "generated_at": "$iso"
  },
  "defaults": {
    "python": ">=3.10",
    "ci": true,
    "publish": "oidc-trusted"
  }
}
`;

export const T_CTXIGNORE = `
# keep ctxpack context lean - nothing generated or vendored
.git/
.venv/
dist/
build/
*.egg-info/
__pycache__/
.mypy_cache/
.pytest_cache/
.ruff_cache/
htmlcov/
*.pyc
`;

export const T_POLICY = `
{
  "version": 1,
  "policies": [
    {
      "id": "P-001",
      "name": "no secrets in repo",
      "severity": "block",
      "check": "secrets-scan"
    },
    {
      "id": "P-002",
      "name": "version tag matches wheel",
      "severity": "block",
      "check": "tag-wheel-guard"
    },
    {
      "id": "P-003",
      "name": "release notes present",
      "severity": "warn",
      "check": "commitlog-entry"
    }
  ]
}
`;

export const T_ROUTES = `
{
  "version": 1,
  "routes": [
    {
      "name": "health",
      "method": "GET",
      "path": "/healthz",
      "status": 200,
      "body": { "ok": true, "service": "$project_name" }
    }
  ]
}
`;

export const T_COMMITLOG = `
{
  "version": 1,
  "project": "$project_name",
  "entries": []
}
`;
